Repository UofTJoonsungPark/Group-261, pull requests merged in 2023-11, with the labels that each got.

#48 changing the data access object for event
  src/app/EventUseCaseFactory.java
  src/data_access/FileEventUserDataAccessObject.java
Labels: enhancement, help wanted

#51 Updated FileEventUserDataAccessObject.writeMaps and Added a Helper Function
  src/data_access/FileEventUserDataAccessObject.java
Labels: enhancement

#58 56 implementing the save event use case backend
  src/data_access/FileEventUserDataAccessObject.java
  src/data_access/FileUserDataAccessObject.java
  src/use_case/signup/SignupInteractor.java
  src/use_case/signup/SignupUserDataAccessInterface.java
Labels: enhancement

#59 57 implementing the save event use case frontend
  src/data_access/FileEventUserDataAccessObject.java
  src/interface_adapter/event/EventController.java
  src/interface_adapter/event/EventPresenter.java
  src/interface_adapter/event/EventState.java
  src/interface_adapter/event/EventViewModel.java
  src/interface_adapter/logged_in/LoggedInPresenter.java
  src/use_case/event/EventInteractor.java
  src/view/EventView.java
Labels: enhancement

#72 Implemented the Back End to Delete an Event.
  src/data_access/FileEventUserDataAccessObject.java
  src/use_case/event/EventDataAccessInterface.java
  src/use_case/event/EventInputData.java
  src/use_case/event/EventInteractor.java
Labels: documentation, enhancement

#85 Implemented createTask and markCompleted
  src/data_access/FileTaskUserDataAccessObject.java
  src/use_case/task/TaskDataAccessInterface.java
  src/use_case/task/TaskInputData.java
  src/use_case/task/TaskInteractor.java
Labels: documentation, enhancement, help wanted
